apiVersion: v1
kind: Service
metadata:
    name: hello-node
spec:
    type: NodePort
    # If you want to expose the service with a Public IP. Then change the type
    # to LoadBalancer and K8s knows what to do.
    #type: LoadBalancer
    selector:
        name: hello-node
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
